name: Deploy Homelab

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Atualizar código
        run: |
          cd /apps/finance/testando-github-actions/teste-actions
          git pull

      - name: Subir aplicação
        run: |
          cd /apps/finance/testando-github-actions/teste-actions
          docker compose down || true
          docker compose up -d --build

